services:
  hello:
    image: hello-img
    build: .
    ports:
      - 8080:8080
    environment:
      ENVIRONMENT_NAME: local
      MONGODB_CONECTION_URL: mongodb://root:example@mongo:27017/
    restart: always
    profiles:
      - "hello-service"
  jenkins:
    image: jenkins/jenkins
    ports:
      - 8082:8080
      - 50000:50000
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - ./Dockerfile:/Dockerfile
    profiles:
      - "hello-service"
    user: 0:0
  mongo:
    image: mongo:5.0.2
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    profiles:
      - "mongo"
  mongo-admin-ui:
    image: mongo-express
    restart: always
    ports:
      - 8090:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: unibuc
      ME_CONFIG_BASICAUTH_PASSWORD: adobe
    profiles:
      - "mongo"
# MONITORING SERVICES
  cadvisor: # container metric prometheus exporter
    image: gcr.io/cadvisor/cadvisor:v0.47.1
    container_name: cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro
    profiles:
      - "monitoring"
  mongodb-exporter:
    build: ./infrastructure/mongodb_exporter/
    command: ./mongodb_exporter-linux-amd64 -logtostderr -mongodb.uri mongodb://root:example@mongo:27017 -groups.enabled 'asserts,durability,background_flusshing,connections,extra_info,global_lock,index_counters,network,op_counters,op_counters_repl,memory,locks,metrics'
    restart: always
    ports:
      - 9001:9001
    profiles:
      - "monitoring"
  loki:
    image: grafana/loki:2.4.1
    ports:
      - 3100:3100
    volumes:
      - ./infrastructure/loki/:/etc/loki/
    command: -config.file=/etc/loki/config.yaml
    profiles:
      - "monitoring"
  prometheus: # metrics aggregation and alert definition server (prometheus server)
    image: prom/prometheus:v2.33.4
    volumes:
      - ./infrastructure/prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/etc/prometheus/durable"
    ports:
      - 9090:9090
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
    profiles:
      - "monitoring"
  alertmanager: # alert manager (prometheus)
    image: prom/alertmanager:v0.23.0
    volumes:
      - ./infrastructure/alertmanager/:/config/
    command: --config.file=/config/alertmanager.yml --log.level=debug
    ports:
      - "9093:9093"
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
    profiles:
      - "monitoring"
  grafana: # dashboard visualisation tool (metrics & logs)
    image: grafana/grafana:8.4.3
    volumes:
      - ./infrastructure/grafana/provisioning:/etc/grafana/provisioning
      - ./infrastructure/grafana/dashboards:/etc/grafana/dashboards
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    profiles:
      - "monitoring"
  wrk-injector-hello-functional: # traffic injector (low)
    image: mtchavez/docker-wrk
    profiles:
      - "perf"
    command: wrk -t4 -c10 -d300s http://hello:8080/hello-world
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
    
  wrk-injector-info-perf: # traffic injector (high)
    image: mtchavez/docker-wrk
    profiles:
      - "perf"
    command: wrk -t4 -c1000 -d5m --timeout 1s --latency http://hello:8080/info
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
