spring:
  datasource:
    url: jdbc:postgresql://postgres_db:5432/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  application:
    name: TripleA

STEAM_API_KEY: 3558248EE7A42726F64B9F420A20A8D8

application:
  security:
    jwt:
      secret-key: rWXmwH1UyBGgF8U8Ytj/50d4PI8NSzyvfqadZSX1K0/eVLkMWRbz5jJGkIvnFoxz
      expiration: 3600000 # 1 hour
      refresh-token:
        expiration: 3600000 # 1 hour
server:
  port: 8080

service-app:
  openapi:
    dev-url: http://localhost:8080
    prod-url: https://localhost:8088

logging:
  level:
    org:
    springframework:
      security: INFO
      web: INFO
      data: INFO
      hibernate: INFO
      jpa: INFO
      sql: INFO
      jwt: INFO
      service-app: INFO